#!/bin/sh

OLD_MOUNT_PATH=/media/sdcard

# 1) Test if symlink already exist
# 2) Cleanup old empty mount points
# 3) Create symlink

if [ -L $OLD_MOUNT_PATH ]; then
  exit 0
fi

DEF_UID=$(grep "^UID_MIN" /etc/login.defs |  tr -s " " | cut -d " " -f2)
DEVICEUSER=$(getent passwd $DEF_UID | sed 's/:.*//')
for path in ${OLD_MOUNT_PATH}/*
do
  rmdir ${path}
done

rmdir ${OLD_MOUNT_PATH}
ln -s /run/media/${DEVICEUSER} ${OLD_MOUNT_PATH}
exit $?
